######################## default configuration ####################
baseURL = "https://www.vihait.com/"

title = "Viha IT Solutions: Delivering Innovative Technology Solutions"
#theme = "main_theme"
# post pagination
paginate = "6"
# post excerpt
summaryLength = "10"
# disqus short name
disqusShortname = "vihait"

[outputs]
home = ["HTML", "RSS", "JSON"]

############################# Plugins ##############################

# CSS Plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "plugins/magnific-popup/magnific-popup.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.css]]
link = "plugins/custom/style.css"

# JS Plugins
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/match-height/jquery.matchHeight-min.js"
[[params.plugins.js]]
link = "plugins/shuffle/shuffle.min.js"
[[params.plugins.js]]
link = "plugins/magnific-popup/jquery.magnific.popup.min.js"
[[params.plugins.js]]
link = "plugins/search/fuse.min.js"
[[params.plugins.js]]
link = "plugins/search/mark.js"
[[params.plugins.js]]
link = "plugins/search/search.js"
[[params.plugins.js]]
link = "plugins/google-map/gmap.js"

############################## navigation ###############################
# main menu
[[menu.main]]
name = "About"
URL = "about"
weight = 1

[[menu.main]]
name = "Portfolio"
URL = "portfolio"
weight = 2

[[menu.main]]
name = "Career"
URL = "career"
weight = 3

#[[menu.main]]
#weight = 3
#name = "Pages"
#hasChildren = true
#
#[[menu.main]]
#parent = "Pages"
#name = "Career"
#URL = "career"
#
#[[menu.main]]
#parent = "Pages"
#name = "Blog"
#URL = "blog"

[[menu.main]]
name = "Contact"
URL = "contact"
weight = 4

# footer menu
[[menu.footer]]
name = "Latest News"
URL = "blog"
weight = 1

[[menu.footer]]
name = "About US"
URL = "about"
weight = 2

[[menu.footer]]
name = "Our Service"
URL = "service"
weight = 3

[[menu.footer]]
name = "Blogs"
URL = "blog"
weight = 4

#################### default parameters ################################
[params]
logo = "images/logo.png"
home = "Home"
# Meta data
description = "Empower your business with cutting-edge mobile solutions. As a leading mobile development company, we specialize in creating innovative and customized mobile apps for iOS and Android. Elevate your user experience, enhance functionality, and stay ahead in the digital landscape with our expert team of mobile developers. From concept to deployment, we bring your ideas to life, delivering seamless and responsive mobile experiences that engage and delight users. Explore our mobile development services and unlock the full potential of your business in the palm of your customers' hands."
author = "Viha IT"
# contact info
address = "4078, Silver Business Point, Near VIP Circle, Digital Valley (Uttran), Surat, Gujarat, India 394105"
mobile = "+91 93779 47677"
email = "ceo@vihait.com"
# contact form action
contact_form_action = "#" # contact form works with https://formspree.io
# Google Analitycs
google_analitycs_id = "" # your id
# search
search = true

# Preloader
[params.preloader]
enable = true
preloader = "" # use jpg, png, svg or gif format.

# Navigation button
[params.navigation_button]
enable = true
label = "get a quote"
link = "contact"

# google map
[params.map]
enable = true
gmap_api = "https://maps.googleapis.com/maps/api/js?key=AIzaSyBu5nZKbeK-WHQ70oqOWo-_4VmwOwKP9YQ"
map_latitude = "51.5223477"
map_longitude = "-0.1622023"
map_marker = "images/marker.png"


###################### Clients logo slider ###############################
[[params.clients_logo]]
logo = "images/clients-logo/clients-logo-1.png"

[[params.clients_logo]]
logo = "images/clients-logo/clients-logo-2.png"

[[params.clients_logo]]
logo = "images/clients-logo/clients-logo-3.png"

#[[params.clients_logo]]
#logo = "images/clients-logo/clients-logo-4.png"
#
#[[params.clients_logo]]
#logo = "images/clients-logo/clients-logo-5.png"

[[params.clients_logo]]
logo = "images/clients-logo/clients-logo-1.png"

[[params.clients_logo]]
logo = "images/clients-logo/clients-logo-2.png"

[[params.clients_logo]]
logo = "images/clients-logo/clients-logo-3.png"

#[[params.clients_logo]]
#logo = "images/clients-logo/clients-logo-4.png"
#
#[[params.clients_logo]]
#logo = "images/clients-logo/clients-logo-5.png"

############################# social icon #################################
[[params.social]]
icon = "ti-facebook" # themify icon pack : https://themify.me/themify-icons
link = "https://www.facebook.com/vihaitsolution"

#[[params.social]]
#icon = "ti-twitter-alt" # themify icon pack : https://themify.me/themify-icons
#link = "#"

[[params.social]]
icon = "ti-linkedin" # themify icon pack : https://themify.me/themify-icons
link = "https://www.linkedin.com/company/vihait/"

#[[params.social]]
#icon = "ti-github" # themify icon pack : https://themify.me/themify-icons
#link = "#"

[[params.social]]
icon = "ti-instagram" # themify icon pack : https://themify.me/themify-icons
link = "https://www.instagram.com/vihaitsolution"

[[params.social]]


[params.footer]
about_us = "About Viha IT Solition"
footer_content = "Viha IT Solution leads in mobile and web development, crafting digital experiences that exceed expectations. Committed to excellence and cutting-edge tech, we redefine possibilities. Join us on a transformative journey into the future of technology."
